version: "3.7"
services:
  mongodb:
    image: mongo:5.0.16
    container_name: docker-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      
  mongo-express:
    image: mongo-express
    container_name: docker-express
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
        ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
        ME_CONFIG_MONGODB_URL: $MONGO_URL
      
  javapp:
    build: .
    container_name: docker-java
    ports:
      - '8102:80'
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
      
